# Docker Volumes
volumes:
    papermc_data:
        name: papermc_data

# Docker services
services:
    # Paper MC
    papermc:
        image: itzg/minecraft-server
        environment:
            EULA: "true"
            TYPE: PAPER
            VERSION: 1.20.4  # Pon la versión a la que quieras tener tu servidor
            # needed for Paper versions before 1.14
            CONSOLE: "true"
            ONLINE_MODE: "true"

        container_name: minecraft-server
        restart: always
        tty: true
        stdin_open: true
        volumes:
            - ./data:/data

        ports:
            - "25565:25565"